### ISSUE TITLE
Racket Users *virtual meetup*

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#11]
APPROVED FOR IMMEDIATE RELEASE

----
### Racket users video meetup

28 November 
30 Minutes

- 11am Pacific Time
- 7pm UK time
- 8pm CET

https://gather.town/app/wH1EDG3McffLjrs0/racket-users *
(Chosen because it allows people to break of into groups if required)
* I've found Safari doesn't work but Firefox and Chrome both work fine.

**Agenda**

- lightning talks(<5 min) - what have you been working on(optional)
- Paper for discussion 
Adding Interactive Visual Syntax to Textual Code by LEIF ANDERSEN, (OOPSLA 2020)
https://arxiv.org/pdf/2010.12695.pdf (pre-reading optional)
- Agree date for next meet-up (every 6-12 weeks?)

Kind regards

Stephen & Sam Phillips

**Comment by pmatos** [comment]
Oh dear  - that came as I was about to press publish.
I will remove this announcement for issue 40.

**Comment by pmatos** [comment]
Removed paragraph: 
```
* Stephen De Gabrielle and Sam Phillips are [organizing a Racket Users Online meetup](https://groups.google.com/g/racket-users/c/caB2EMsUr3Y/m/kp_OWl1SAwAJ) to happen on a regular basis - put it in your calendar - first one will be November 28, 2020 at 1pm PT (9pm GMT).
```

 To be added in the future.

**Comment by spdegabrielle** [comment]
APPROVED FOR IMMEDIATE RELEASE
@samph

**Comment by pmatos** [comment]
Thanks.
