### ISSUE TITLE
DrRacket Quickscript updates

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#30]
Updates for some quickscripts:

- [url2script](https://gist.github.com/Metaxal/77391e388303af5513d09bcd640f116c) Easily install quickscripts found in gists, gitlab snippets, pasterack and pastebin. Also, url2script just got a lot smarter: It can update a script that has been downloaded with url2script. This was implemented by adding a sub-module at the end of the file that contains the url of the original script. Installation: `Scripts|Manage scripts|New…`, type `url2script`, then paste the content of the script at the url above in place of the default template, save, and finally `Scripts|Manage scripts|Reload menu`. How to use: _to install a new script from (say) gist, just run the url2script, paste in the url of the target script, type a script name (the default directory is fine) and reload the menu._

- [Workspaces for DrRacket (quickscript)](https://gist.github.com/Metaxal/f5ea8e94b802eac947fe9ea72870624b)  See also @sorawee's related plugin [Restore workspace for DrRacket](https://github.com/sorawee/drracket-restore-workspace)

- [open multiple files at once](https://gist.github.com/Metaxal/3ed323747e1af0bd4df5acd56b03b45e)

- [open-recent](https://github.com/Quickscript-Competiton/July2020entries/blob/master/scripts/open-recent.rkt) can open multiple files, by unchecking the checkbox at the bottom.

Questions? Answers at the #DrRacket slack channel.

**Comment by Metaxal** [comment]
How about:
* [url2script](https://gist.github.com/Metaxal/77391e388303af5513d09bcd640f116c): A script to install and update(new!) other (quick)scripts found on gists, gitlab snippets, pasterack, etc. Installation: ...

**Comment by Metaxal** [comment]
Also, open-recent is part of the `quickscript-competition-2020` package, so one just needs to use `raco pkg install ...` or `raco pkg update ...` for this one.
So maybe something like:
* open-recent: blabla (install or update the [`quickscript-competition-2020`](https://pkgs.racket-lang.org/package/quickscript-competition-2020) package)
