### ISSUE TITLE
Tip: Video from Chaos Computer Club: building a language/BASIC with Racket

### ISSUE THREAD

**Issue by haijinSk** [pmatos/racket-news#31]
[All Programming Language Suck? Just Build Your Own! – Language-Oriented Programming with Racket](https://media.ccc.de/v/rc3-257534-all_programming_language_suck_just_build_your_own_language_oriented_programming_with_racket#t=3000)

**Comment by pmatos** [comment]
Thanks Peter - Will get it in, into today's issue.

**Comment by haijinSk** [comment]
Thank you.
