### ISSUE TITLE
Racket Discord goes bot crazy!

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#35]
### Racket Discord goes bot crazy!
An example bot for Discord [R16](https://git.sr.ht/~williewillus/r16/) by Alwinfy, Vincent Lee @williewillus and Benedek Szilvasy @eutro allows users to register and execute short code snippets in a sandbox from Discord commands.  (Peek behind the curtain and you will see it is using the [racket-cord](https://pkgs.racket-lang.org/package/racket-cord) package by Ben Simms, with contributions from Benedek Szilvasy @eutro  Vincent Lee @williewillus .)

[Join the Racket discord](Racket discord invite link https://discord.gg/6Zq8sH5) and try it on the `#bots` channel:

`!rkt eval (require math/number-theory) (factorize 120)`

or try the `!!instant-tshirt` command:

```
!!instant-tshirt (cons
  'Racket
  'News)
  ```
 ![image](https://user-images.githubusercontent.com/108047/109419649-6e8aae80-79c6-11eb-8680-72311c91139e.png)

Are you working on a bot package for another platform? Maybe IRC, Slack, Reddit or something else?

Stephen De Gabrielle

**Comment by spdegabrielle** [comment]
@williewillus , @eutropius225 and Alwinfy - would you prefer your real names?

**Comment by spdegabrielle** [comment]
@pmatos can we have the image of the t-shirt  in RacketNews?

**Comment by williewillus** [comment]
Having both is fine with me (Vincent Lee @williewillus)

**Comment by eutro** [comment]
I would be fine with both as well (Benedek Szilvasy @eutro) - note that I've changed my username since this issue was created.

**Comment by pmatos** [comment]
> @pmatos can we have the image of the t-shirt in RacketNews?

Sure.

**Comment by pmatos** [comment]
Thanks - I left the mention of `racket-cord` to next issue so I can use it as a featured project. :)
