### ISSUE TITLE
Racket Meet up at new time

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#37]
DRAFT - DO NOT Publish 
--

We are going to try a session that is two hours later.
_CEST attendees indicated that 10pm is not too late, and 9pm in the UK might not conflict with family dinner time._

**[Sat, 3 Apr 2021 UTC at 20:00](https://www.timeanddate.com/worldclock/converter.html?iso=20210403T200000&p1=204&p2=136&p3=179&p4=224):** 
* Prague: 22:00 CEST
* London: 21:00 BST
* New York: 16:00 EDT
* San Francisco: 13:00 PDT
 
**Location**: https://gather.town/app/wH1EDG3McffLjrs0/racket-users 

Agenda. (more of a set of suggestions and talking points than a strict agenda)
* What have you been working on?
* Papers/package for discussion
* items from latest [Racket News](https://racket-news.com/)

**Comment by spdegabrielle** [comment]
@samdphillips

trying another time

**Comment by pmatos** [comment]
@spdegabrielle 
Is this still draft? Or can it be published?
