### ISSUE TITLE
Help get Racket Stories to 500 links

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#38]
—
Hi All,

[Racket Stories](https://racket-stories.com) has close to 400 links to Racket related stuff.

Help me get to 500.

Submit blog posts, libraries, one off Racket hacks, ...

New or old doesn't matter - if it is interesting to you, it's probably interesting to others as well.

Don't forget to vote on the stories.

/soegaard

**Comment by soegaard** [comment]
"one of" -> "one-off"
