### ISSUE TITLE
DrRacket Quickscript of the day

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#53]
## DrRacket Quickscript of the day
Quickscript (featured project of issue 38) provides an easy way to extend DrRacket with small Racket scripts to automate some actions in the editor, while avoiding the need to restart DrRacket. In this new section, contributed by Stephen De Gabrielle, we will be highlighting some of the most interesting scripts out there. Do you have a favourite script? Share it with us!

I'd like to thank Thorsten Blum for this weeks quickscript '**Remove trailing whitespace**' that removes trailing spaces from the selected text:
```
#lang racket/base
(require quickscript racket/string)
(define-script whitespace
  #:label "Remove trailing whitespace"
  (λ (selection)
    (let ([linebreak (string #\newline)])
      (string-join
       (map (λ (line)
              (string-trim line #px"\\s+" #:left? #f))
            (string-split selection linebreak))
       linebreak))))
```
published at https://github.com/toblux/quickscript-user-scripts

Installation: you can paste this into a new script via the menu: Scripts > Manage > New

Get started at the Racket Wiki: [Quickscript Scripts for DrRacket](https://github.com/racket/racket/wiki/Quickscript-Scripts-for-DrRacket)

Full documentation at https://docs.racket-lang.org/quickscript/.

**Comment by spdegabrielle** [comment]
EMBARGOED removed on approval from Thorsten Blum via slack

**Comment by Metaxal** [comment]
May be worth saying that it removes the trailing spaces in the selected text. (Otherwise one may try it without selecting anything and wonder why it 'fails'.)

**Comment by toblux** [comment]
I've just published the script at https://github.com/toblux/quickscript-user-scripts if that helps.

**Comment by spdegabrielle** [comment]
@pmatos this is PRESS READY now 😀
