### ISSUE TITLE
Racket Slack Archive

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#55]
> The latest version of the archive is up-and-running at https://benknoble.github.io/racket-slack-archive/ (extends through roughly 2021-05-16). The site is now built using a mix of Racket (data processing) and Jekyll/Ruby (site-generation). I have some todos to make a nicer experience, and help is welcome. (Also if anyone wants to start working porting the Jekyll + Ruby stuff to Racket, feel free.)
—- @benknoble

The signup for the Racket Slack is at  [https://racket-slack.herokuapp.com/](https://racket-slack.herokuapp.com/)

**Comment by benknoble** [comment]
In fact the archive now runs through roughly the 7th of June this year. If you want to get involved, the repository is https://github.com/benknoble/racket-slack-archive

**Comment by pmatos** [comment]
Given the issues surrounding privacy and the code being taken down, i am closing this.

**Comment by benknoble** [comment]
If/when I get it up and running appropriately, I'll let you know.

**Comment by pmatos** [comment]
> If/when I get it up and running appropriately, I'll let you know.

Thanks

**Comment by benknoble** [comment]
It's back! https://benknoble.github.io/racket-slack-archive/ Contribute to the site via the public archive-viewer project (https://github.com/benknoble/slack-archive-viewer)

**Comment by benknoble** [comment]
PS the original message contains a quote of one of my messages; the "I" there is me

**Comment by spdegabrielle** [comment]
My apologies. 
I can’t unclose this issue so it might be easier to do a new one for the next issue @benknoble

**Comment by benknoble** [comment]
@pmatos Surely can reopen if need be. If they would prefer I create a new issue, I will.

**Comment by pmatos** [comment]
> @pmatos Surely can reopen if need be. If they would prefer I create a new issue, I will. 

Reopened, thanks.
