### ISSUE TITLE
something news for sauron

### ISSUE THREAD

**Issue by dannypsnl** [pmatos/racket-news#56]
1. it can jump to cross-file definition correctly now(only for the project-internal files now)
    - and cmd+shift+b can jump back to the previous position 
2. it can formatting file on-save(call tabify and remove trailing spaces)
3. it can close the untitled tab automatically

**Comment by pmatos** [comment]
Thanks @dannypsnl . That'll will fit really well with making Sauron the Featured Project of issue 52, thanks.
