### ISSUE TITLE
collector - generate Gentoo ebuild scripts from Racket catalog packages, version 2

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#61]
**collector** - generate Gentoo ebuild scripts from Racket catalog packages, version 2
https://gitlab.com/src_prepare/collector2

From @xgqt via #show-and-tell on the Racket Discord https://discord.gg/6Zq8sH5

**Comment by xgqt** [comment]
Hi! Nice to get tagged here :D

Just warning: VERY experimental!
BUT IT WORKS!
The "portage overlay" (essentially a Linux package repository) is available here: 
https://gitlab.com/src_prepare/rkt
And it is usable, atm I have some packages installed from it.

![image](https://user-images.githubusercontent.com/47485207/122685001-792cb600-d1f8-11eb-91b8-3be9529d0c6d.png)

**Comment by spdegabrielle** [comment]
apologies - duplicate

**Comment by xgqt** [comment]
yes, this was already featured in https://racket-news.com/2021/06/racket-news-issue-51.html
