### ISSUE TITLE
ANN: Tabular Asa

### ISSUE THREAD

**Issue by massung** [pmatos/racket-news#66]
I just released [Tabular Asa](https://pkgd.racket-lang.org/pkgn/package/tabular-asa) - an efficient, column-oriented, immutable dataframes implementation for Racket. Feature set includes:

* B-tree indexes (scannable)
* Generic sorting (an orderable generic type)
* Joining (inner & outer)
* Grouping
* Aggregating
* Everything is a sequence: tables, columns, indexes, groups, etc.
* Read/write CSV & JSON (columns, records, and lines)

The code is also written to be threaded and combine nicely with the `plot` module. For example:

```racket
(plot (discrete-histogram (~> (call-with-input-file "books.csv" table-read/csv)
                              (table-groupby '(Genre))
                              (group-count)
                              (table-cut '(Genre Title))
                              (table-rows))))
```

**Comment by pmatos** [comment]
Thanks.
