### ISSUE TITLE
Restarting the Racket Video Meetup

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#69]
Restarting the Racket Video Meetup

Where: https://gather.town/app/wH1EDG3McffLjrs0/racket-users

When: First Saturday EVERY Month UTC: 20:00 (30 minutes but can overrun)
Calendar: [Google](https://calendar.google.com/calendar/embed?src=a6a7g9sg739gjfeak6ilkh8fdc%40group.calendar.google.com&ctz=Europe%2FLondon) [iCal](https://calendar.google.com/calendar/ical/a6a7g9sg739gjfeak6ilkh8fdc%40group.calendar.google.com/public/basic.ics)

The next meetup is 

- London, United Kingdom    Sat, 2 Oct 2021 at 21:00 BST     
- Prague, Czechia           Sat, 2 Oct 2021 at 22:00 CEST    
- New York, USA             Sat, 2 Oct 2021 at 16:00 EDT     
- San Francisco, USA        Sat, 2 Oct 2021 at 13:00 PDT     
- Corresponding UTC         Sat, 2 Oct 2021 at 20:00         

https://www.timeanddate.com/worldclock/converter.html?iso=20211002T200000&p1=136&p2=204&p3=179&p4=224

**Comment by pmatos** [comment]
Thanks.
