### ISSUE TITLE
Racket Meetup: Saturday December 4

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#74]
Racket Meetup: Saturday December 4

Where: https://gather.town/app/wH1EDG3McffLjrs0/racket-users

When: First Saturday EVERY Month UTC: 20:00 (30 minutes but can overrun)

The next meetup is

Pacific Time, PT          Sat, 4 Dec 2021 at 12:00 PST    
Mountain Time, MT         Sat, 4 Dec 2021 at 13:00 MST    
Central Time, CT          Sat, 4 Dec 2021 at 14:00 CST    
Eastern Time, ET          Sat, 4 Dec 2021 at 15:00 EST    
London, United Kingdom    Sat, 4 Dec 2021 at 20:00 GMT    
Prague, Czechia           Sat, 4 Dec 2021 at 21:00 CET    
Corresponding UTC         Sat, 4 Dec 2021 at 20:00        

https://www.timeanddate.com/worldclock/converter.html?iso=20211204T200000&p1=tz_pt&p2=tz_mt&p3=tz_ct&p4=tz_et&p5=136&p6=204

Google calendar: https://calendar.google.com/calendar/embed?src=a6a7g9sg739gjfeak6ilkh8fdc%40group.calendar.google.com&ctz=Europe%2FLondon

iCal: https://calendar.google.com/calendar/ical/a6a7g9sg739gjfeak6ilkh8fdc%40group.calendar.google.com/public/basic.ics

https://racket.discourse.group/t/racket-meetup-saturday-december-4/130?u=spdegabrielle

**Comment by pmatos** [comment]
Cleanup. This is old.
