### ISSUE TITLE
Racket Advent of Code leaderboard (starts 1 Dec)

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#75]
Racket AOC leaderboard

Advent of Code starts 1 Dec

Any Racket ecosystem language is fine. This includes languages that target other platforms like RacketScript and Urlang.

Racket leaderboard key: 22197-a7a01707.

Racket Discourse: https://racket.discourse.group/t/advent-of-code-2021-racket-leaderboard/118?u=spdegabrielle

**Comment by pmatos** [comment]
Cleanup. This is old.
