### ISSUE TITLE
Racket version 8.3 is also now available from the Ubuntu PPA

### ISSUE THREAD

**Issue by spdegabrielle** [pmatos/racket-news#76]
Racket version 8.3 is also now available from the Ubuntu PPA
at  https://launchpad.net/~plt/+archive/ubuntu/racket 

Supports Ubuntu 21.10 (Impish). 

Please report any issues on github: https://github.com/takikawa/racket-ppa/issues 
(thank you Asumu!)

**Comment by pmatos** [comment]
Cleanup. This is old.
