### ISSUE TITLE
New book:  Daniel Jackson: The Essence of Software: Why Concepts Matter for Great Design

### ISSUE THREAD

**Issue by haijinSk** [pmatos/racket-news#78]
Daniel Jackson is one of the men mentioned in the book How to Design Programs:

"We drew inspiration from Michael Jackson’s method for creating COBOL programs plus conversations with Daniel Friedman on recursion, Robert Harper on type theory, and **Daniel Jackson on software design**."

http://htdp.org/2021-11-15/Book/part_preface.html

The new book, The Essence of Software, is not directly related to Racket, nor Scheme but I think it is cool and important... 

https://press.princeton.edu/books/hardcover/9780691225388/the-essence-of-software
https://www.youtube.com/watch?v=8a3P-YWUSGk
https://www.amazon.com/Essence-Software-Concepts-Matter-Design/dp/0691225389

**Comment by spdegabrielle** [comment]
I agreed about the book but Michael Jackson != Daniel Jackson

**Comment by spdegabrielle** [comment]
That was embarrassing
