### ISSUE TITLE
New book using Racket (student languages): Animated Problem Solving: An Introduction to Program Design Using Video Game Development by Marco T. Morazán 

### ISSUE THREAD

**Issue by haijinSk** [pmatos/racket-news#82]
https://www.amazon.com/Animated-Problem-Solving_-An-Introduction-to-Program-Design-Using-Video-Game-Development-_Texts-in-Computer-Science_/dp/3030850900

https://www.springerprofessional.de/en/animated-problem-solving/20029642

Marco T. Morazán, Ph.D.: https://www.shu.edu/profiles/marcomorazan.cfm

**Comment by pmatos** [comment]
Hi @haijinSk, Does this book use Racket?

**Comment by spdegabrielle** [comment]
yes, DrRacket and HTDP student languages

**Comment by haijinSk** [comment]
Hello, glad to see racket-news are alive, and as @spdegabrielle wrote, yes and for example Matthias Felleisen wrote:

“Marco Morazán has delivered a book for the freshman year that takes readers further than any other book. It introduces complete novices to the discipline of systematically designing programs. Almost on the sly, the book shows the reader how to create multi-player video games using iterative refinement and in the process clearly explains the concept of a synchronization bug, one of the most subtle problems of contemporary system development. The power of the approach is amazing. And you, dear young reader, are in for a treat.” 

Thank you.
